// <auto-generated />
namespace Banking.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTransactionDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTransactionDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201404130033341_AddTransactionDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
