// <auto-generated />
namespace Banking.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddInvestments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInvestments));
        
        string IMigrationMetadata.Id
        {
            get { return "201403130146513_AddInvestments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
