// <auto-generated />
namespace Banking.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201404010136386_Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
